name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  image_picker: ^1.1.2
  image: ^4.0.17  # Pour la compression d'images
  http: ^1.1.0
  # ðŸ”¥ MISE Ã€ JOUR FIREBASE - versions compatibles
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.13.4      # Ajoutez pour la base de donnÃ©es
  # Localization
  easy_localization: ^3.0.7
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  # Theme / State management
  provider: ^6.1.0

  # Authentication helpers
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.0.0


  # ML Kit (compatible versions!)
  google_mlkit_face_detection: ^0.13.0
  google_mlkit_selfie_segmentation: ^0.10.0
  google_ml_kit: ^0.20.0
  google_mlkit_subject_segmentation: ^0.0.2
  google_mlkit_image_labeling: ^0.14.1
  google_mlkit_commons: ^0.11.0
  # File system
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/translations/en.json
    - lib/translations/fr.json
    - lib/assets/fish.png